blank_issues_enabled: true
contact_links:
  - name: Ask a question or suggest something
    url: https://github.com/andyboltondev/torchbound-labyrinth/discussions
    about: For ideas, questions and anything that is not a bug.
