// Build identity. GENERATED by tools/stamp_version.py -- do not hand-edit.
//
// The version number is the game's, bumped in version.json; the rest of the
// stamp identifies the exact build, so a screenshot of the pause menu is
// enough to find the commit it came from.

export const VERSION = {
  number: '1.4.0',
  codename: 'Grindstone',
  build: '20260828-212650',
  commit: 'a2bb133',
  branch: 'master',
  pr: null,
};

// What the menus show: "Build 1.2.0-20260826-213242".
export const BUILD_STRING = 'Build ' + VERSION.number + '-' + VERSION.build;

// The long form, for the pause menu and bug reports.
export const BUILD_DETAIL = VERSION.commit
  + (VERSION.pr ? '  ·  PR #' + VERSION.pr : '')
  + (VERSION.branch && VERSION.branch !== 'master' ? '  ·  ' + VERSION.branch : '');
