#!/usr/bin/env python3
"""Stamp the build identity into src/core/version.js.

The game has no build step, so the version module is a committed source file
rather than something generated at load time. This script rewrites it from
three inputs:

  * version.json   -- the semantic version, bumped by hand when the game
                      changes in a way players would notice.
  * the clock      -- a UTC build timestamp, yyyymmdd-hhmmss.
  * git            -- the commit the build was cut from, its branch, and the
                      pull request number when one is known.

Run it before committing so the number in the menus matches the code, and
again in CI at deploy time so the live build reports when it actually shipped
and which commit it came from.

    python tools/stamp_version.py                 # stamp from the working tree
    python tools/stamp_version.py --pr 7          # record a pull request
    python tools/stamp_version.py --check         # non-zero if it is stale
"""

import argparse
import datetime
import json
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGET = ROOT / 'src' / 'core' / 'version.js'
SOURCE = ROOT / 'version.json'

TEMPLATE = '''// Build identity. GENERATED by tools/stamp_version.py -- do not hand-edit.
//
// The version number is the game's, bumped in version.json; the rest of the
// stamp identifies the exact build, so a screenshot of the pause menu is
// enough to find the commit it came from.

export const VERSION = {
  number: '%(number)s',
  codename: '%(codename)s',
  build: '%(build)s',
  commit: '%(commit)s',
  branch: '%(branch)s',
  pr: %(pr)s,
};

// What the menus show: "Build 1.2.0-20260826-213242".
export const BUILD_STRING = 'Build ' + VERSION.number + '-' + VERSION.build;

// The long form, for the pause menu and bug reports.
export const BUILD_DETAIL = VERSION.commit
  + (VERSION.pr ? '  \u00b7  PR #' + VERSION.pr : '')
  + (VERSION.branch && VERSION.branch !== 'master' ? '  \u00b7  ' + VERSION.branch : '');
'''


def git(*args, default=''):
    try:
        out = subprocess.run(('git',) + args, cwd=ROOT, capture_output=True, text=True, timeout=15)
    except (OSError, subprocess.SubprocessError):
        return default
    return out.stdout.strip() if out.returncode == 0 else default


def detect_pr(explicit):
    if explicit:
        return str(int(explicit))
    # GitHub Actions exposes the pull request as refs/pull/<n>/merge.
    ref = os.environ.get('GITHUB_REF', '')
    m = re.match(r'refs/pull/(\d+)/', ref)
    if m:
        return m.group(1)
    return 'null'


def build_stamp(pr=None, when=None):
    meta = json.loads(SOURCE.read_text(encoding='utf-8'))
    when = when or datetime.datetime.now(datetime.timezone.utc)
    branch = os.environ.get('GITHUB_HEAD_REF') or git('rev-parse', '--abbrev-ref', 'HEAD', default='detached')
    return TEMPLATE % {
        'number': meta['version'],
        'codename': meta.get('codename', ''),
        'build': when.strftime('%Y%m%d-%H%M%S'),
        'commit': git('rev-parse', '--short=7', 'HEAD', default='0000000'),
        'branch': branch,
        'pr': detect_pr(pr),
    }


def stamped_fields(text):
    """The parts of a stamp --check can meaningfully compare.

    Only the semantic version, because that is the one field a human is
    expected to keep in step with version.json. The timestamp, commit and
    branch all differ legitimately between a developer's tree and a CI
    checkout (which builds a merge commit), so comparing them would make the
    check fail on every pull request.
    """
    return re.findall(r"(?:number|codename): '[^']*'", text)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--pr', help='pull request number to record')
    ap.add_argument('--check', action='store_true',
                    help='exit non-zero if the stamp does not match the tree')
    args = ap.parse_args()

    fresh = build_stamp(args.pr)
    if args.check:
        if not TARGET.exists():
            print('version.js is missing; run tools/stamp_version.py', file=sys.stderr)
            return 1
        current = TARGET.read_text(encoding='utf-8')
        if stamped_fields(current) != stamped_fields(fresh):
            print('version.js is stale; run tools/stamp_version.py', file=sys.stderr)
            return 1
        print('version.js is current')
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(fresh, encoding='utf-8')
    m = re.search(r"build: '([^']*)'", fresh)
    n = re.search(r"number: '([^']*)'", fresh)
    print('Build %s-%s' % (n.group(1), m.group(1)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
