#!/usr/bin/env python3
"""Stamp the build identity into src/core/version.js.

The game has no build step, so the version module is a committed source file
rather than something generated at load time. This script rewrites it from
three inputs:

  * version.json   -- the semantic version, bumped by hand when the game
                      changes in a way players would notice.
  * the clock      -- a UTC build timestamp, yyyymmdd-hhmmss.
  * git            -- the commit the build was cut from, its branch, and the
                      pull request number when one is known.

Run it before committing so the number in the menus matches the code, and
again in CI at deploy time so the live build reports when it actually shipped
and which commit it came from.

    python tools/stamp_version.py                 # stamp from the working tree
    python tools/stamp_version.py --pr 7          # record a pull request
    python tools/stamp_version.py --check         # non-zero if it is stale
"""

import argparse
import datetime
import json
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGET = ROOT / 'src' / 'core' / 'version.js'
SOURCE = ROOT / 'version.json'
MANIFEST = ROOT / 'build.json'

# What the service worker precaches, and what the page reads to find out
# whether the build it is running is still the current one. Generated here
# rather than written by hand in sw.js: a project with no bundler has no other
# moment at which the full file list is known, and a hand-kept list is a list
# that goes stale one module at a time and takes offline play down with it
# without ever saying so.
ASSET_ROOTS = ('src', 'icons')
ASSET_FILES = ('index.html', 'manifest.webmanifest')
ASSET_SUFFIXES = ('.js', '.css', '.json', '.png', '.svg', '.woff2')

TEMPLATE = '''// Build identity. GENERATED by tools/stamp_version.py -- do not hand-edit.
//
// The version number is the game's, bumped in version.json; the rest of the
// stamp identifies the exact build, so a screenshot of the pause menu is
// enough to find the commit it came from.

export const VERSION = {
  number: '%(number)s',
  codename: '%(codename)s',
  build: '%(build)s',
  commit: '%(commit)s',
  branch: '%(branch)s',
  pr: %(pr)s,
};

// What the menus show: "Build 1.2.0-20260826-213242".
export const BUILD_STRING = 'Build ' + VERSION.number + '-' + VERSION.build;

// The long form, for the pause menu and bug reports.
export const BUILD_DETAIL = VERSION.commit
  + (VERSION.pr ? '  \u00b7  PR #' + VERSION.pr : '')
  + (VERSION.branch && VERSION.branch !== 'master' ? '  \u00b7  ' + VERSION.branch : '');
'''


def git(*args, default=''):
    try:
        out = subprocess.run(('git',) + args, cwd=ROOT, capture_output=True, text=True, timeout=15)
    except (OSError, subprocess.SubprocessError):
        return default
    return out.stdout.strip() if out.returncode == 0 else default


def detect_pr(explicit):
    if explicit:
        return str(int(explicit))
    # GitHub Actions exposes the pull request as refs/pull/<n>/merge.
    ref = os.environ.get('GITHUB_REF', '')
    m = re.match(r'refs/pull/(\d+)/', ref)
    if m:
        return m.group(1)
    return 'null'


def build_stamp(pr=None, when=None):
    meta = json.loads(SOURCE.read_text(encoding='utf-8'))
    when = when or datetime.datetime.now(datetime.timezone.utc)
    branch = os.environ.get('GITHUB_HEAD_REF') or git('rev-parse', '--abbrev-ref', 'HEAD', default='detached')
    return TEMPLATE % {
        'number': meta['version'],
        'codename': meta.get('codename', ''),
        'build': when.strftime('%Y%m%d-%H%M%S'),
        'commit': git('rev-parse', '--short=7', 'HEAD', default='0000000'),
        'branch': branch,
        'pr': detect_pr(pr),
    }


def collect_assets():
    """Every file the game is made of, as root-relative URLs, sorted.

    Deliberately narrow: the page, its manifest and icons, the source tree, and
    nothing else. An installed copy has to be able to draw its own icon and
    read its own manifest with no connection, or the home-screen tile is the
    one part of the game that needs the network. The test
    page, the tools and the shots directory are development furniture and have
    no business being carried onto a player's device -- and build.json is left
    out on purpose, because it is the one file that must always come from the
    network or the game can never learn it is out of date.
    """
    urls = set()
    for name in ASSET_FILES:
        if (ROOT / name).is_file():
            urls.add('./' + name)
    for root in ASSET_ROOTS:
        base = ROOT / root
        if not base.is_dir():
            continue
        for path in base.rglob('*'):
            if not path.is_file() or path.suffix not in ASSET_SUFFIXES:
                continue
            urls.add('./' + path.relative_to(ROOT).as_posix())
    return sorted(urls)


def write_manifest(stamp_text):
    """build.json: what the service worker caches, and the freshness probe.

    The build string is the cache's name, so a new build is a new cache and
    there is never a half-updated mixture of old and new modules importing each
    other. It is also what the running page compares itself against to decide
    whether an update is waiting.
    """
    build = re.search(r"build: '([^']*)'", stamp_text).group(1)
    number = re.search(r"number: '([^']*)'", stamp_text).group(1)
    payload = {
        'version': number,
        'build': build,
        'assets': collect_assets(),
    }
    MANIFEST.write_text(json.dumps(payload, indent=2) + '\n', encoding='utf-8')
    return build


def stamped_fields(text):
    """The parts of a stamp --check can meaningfully compare.

    Only the semantic version, because that is the one field a human is
    expected to keep in step with version.json. The timestamp, commit and
    branch all differ legitimately between a developer's tree and a CI
    checkout (which builds a merge commit), so comparing them would make the
    check fail on every pull request.
    """
    return re.findall(r"(?:number|codename): '[^']*'", text)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--pr', help='pull request number to record')
    ap.add_argument('--check', action='store_true',
                    help='exit non-zero if the stamp does not match the tree')
    args = ap.parse_args()

    fresh = build_stamp(args.pr)
    if args.check:
        if not TARGET.exists():
            print('version.js is missing; run tools/stamp_version.py', file=sys.stderr)
            return 1
        current = TARGET.read_text(encoding='utf-8')
        if stamped_fields(current) != stamped_fields(fresh):
            print('version.js is stale; run tools/stamp_version.py', file=sys.stderr)
            return 1
        if not MANIFEST.exists():
            print('build.json is missing; run tools/stamp_version.py', file=sys.stderr)
            return 1
        # The offline cache is only as complete as this list, and the list is
        # only regenerated when somebody remembers to stamp. Catching a new
        # module here is the difference between "offline play is missing one
        # file" and finding out from a player.
        stored = json.loads(MANIFEST.read_text(encoding='utf-8')).get('assets', [])
        if stored != collect_assets():
            print('build.json does not list the current source tree; '
                  'run tools/stamp_version.py', file=sys.stderr)
            return 1
        print('version.js and build.json are current')
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(fresh, encoding='utf-8')
    write_manifest(fresh)
    m = re.search(r"build: '([^']*)'", fresh)
    n = re.search(r"number: '([^']*)'", fresh)
    print('Build %s-%s  (%d files cached for offline play)'
          % (n.group(1), m.group(1), len(collect_assets())))
    return 0


if __name__ == '__main__':
    sys.exit(main())
